import { Sweet, User } from '@/types';

export const mockUser: User = {
  id: '1',
  email: 'admin@sweetshop.com',
  name: 'Sweet Admin',
  role: 'admin',
  createdAt: new Date().toISOString(),
};

export const mockSweets: Sweet[] = [
  {
    id: '1',
    name: 'Belgian Dark Chocolate Truffles',
    category: 'Chocolates',
    price: 12.99,
    quantity: 50,
    description: 'Luxurious dark chocolate truffles handcrafted with premium Belgian cocoa.',
    image: '/sweets/chocolate-truffles.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Rainbow Gummy Bears',
    category: 'Gummies',
    price: 5.99,
    quantity: 120,
    description: 'Colorful assortment of fruity gummy bears in six delicious flavors.',
    image: '/sweets/gummy-bears.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Strawberry Swirl Lollipops',
    category: 'Lollipops',
    price: 2.49,
    quantity: 0,
    description: 'Classic spiral lollipops with a sweet strawberry cream taste.',
    image: '/sweets/lollipops.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Salted Caramel Bonbons',
    category: 'Candies',
    price: 8.99,
    quantity: 75,
    description: 'Buttery caramel candies with a hint of sea salt.',
    image: '/sweets/caramel-bonbons.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Double Chocolate Chip Cookies',
    category: 'Cookies',
    price: 6.99,
    quantity: 40,
    description: 'Freshly baked cookies loaded with dark and milk chocolate chips.',
    image: '/sweets/chocolate-cookies.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'French Macarons Assortment',
    category: 'Pastries',
    price: 15.99,
    quantity: 30,
    description: 'Delicate French macarons in raspberry, vanilla, pistachio, and chocolate.',
    image: '/sweets/macarons.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Milk Chocolate Hearts',
    category: 'Chocolates',
    price: 9.99,
    quantity: 85,
    description: 'Heart-shaped milk chocolates perfect for gifting or self-indulgence.',
    image: '/sweets/chocolate-hearts.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Sour Worm Gummies',
    category: 'Gummies',
    price: 4.49,
    quantity: 100,
    description: 'Tangy and chewy sour worms coated in sweet-sour sugar.',
    image: '/sweets/sour-worms.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
